// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYScJ_u-DSL99NVjF2OoFVLVHEEPNgYb8',
    appId: '1:880117710239:web:8d52b49a603269e58551aa',
    messagingSenderId: '880117710239',
    projectId: 'fluttercourse-31955',
    authDomain: 'fluttercourse-31955.firebaseapp.com',
    storageBucket: 'fluttercourse-31955.firebasestorage.app',
    measurementId: 'G-HFP65K4L7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAf2v_KbLTn40QC6LoHCc28IPCqSUIPsU',
    appId: '1:880117710239:android:91041cecc7631ae98551aa',
    messagingSenderId: '880117710239',
    projectId: 'fluttercourse-31955',
    storageBucket: 'fluttercourse-31955.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOQzyRaizGmbL_MjpyKaLjj0feSm3RC5E',
    appId: '1:880117710239:ios:fe6eb47cd1516db88551aa',
    messagingSenderId: '880117710239',
    projectId: 'fluttercourse-31955',
    storageBucket: 'fluttercourse-31955.firebasestorage.app',
    iosBundleId: 'com.example.app22',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOQzyRaizGmbL_MjpyKaLjj0feSm3RC5E',
    appId: '1:880117710239:ios:fe6eb47cd1516db88551aa',
    messagingSenderId: '880117710239',
    projectId: 'fluttercourse-31955',
    storageBucket: 'fluttercourse-31955.firebasestorage.app',
    iosBundleId: 'com.example.app22',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYScJ_u-DSL99NVjF2OoFVLVHEEPNgYb8',
    appId: '1:880117710239:web:3381a9e293b9a4bd8551aa',
    messagingSenderId: '880117710239',
    projectId: 'fluttercourse-31955',
    authDomain: 'fluttercourse-31955.firebaseapp.com',
    storageBucket: 'fluttercourse-31955.firebasestorage.app',
    measurementId: 'G-P3QZ66RQD8',
  );
}
